### ISSUE TITLE
Create Project bug

### ISSUE THREAD

**Issue by tharris9d** [valadas/Eraware_Dnn_Templates#427]
Hi Daniel, 
![image](https://user-images.githubusercontent.com/217445/148659305-1f774dea-7375-4b53-973e-2b27b30bb973.png)
I am getting this error when trying to create a new project. I used the install version and also downloaded the source and compiled to a vsix but I get the same error. Am I missing a dependency?
Thanks, 
Tom Harris

**Comment by valadas** [comment]
Strange, but I might have a clue, I hard some hard time with versioning and may have broken something with references, I'll take a look at that shortly...

**Comment by tharris9d** [comment]
😊Thanks!

**Comment by valadas** [comment]
Ok, can you try this one @tharris9d and let me know how that goes...

https://github.com/valadas/Eraware_Dnn_Templates/releases/tag/v1.1.0-rc1

**Comment by tharris9d** [comment]
I was able to create the project with the updated Template. However when I build (debug package) I get these errors
Creating directory 'E:\Code\MyModule1\MyModule1\.nuke\temp'...
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Nuke.Common.ProjectModel.SolutionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
Creating directory 'E:\Code\MyModule1\MyModule1\.github\workflows'...
Creating directory 'E:\Code\MyModule1\MyModule1\.github\workflows'...
Creating directory 'E:\Code\MyModule1\MyModule1\.github\workflows'...
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Exception has been thrown by the target of an invocation.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Nuke.Common.ProjectModel.SolutionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Nuke.Common.ProjectModel.SolutionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
Exception has been thrown by the target of an invocation.
StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Nuke.Common.ProjectModel.SolutionAttribute.GetValue(MemberInfo member, Object instance)
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.<>c__DisplayClass0_0.<TryGetValue>b__0()
The SDK 'Microsoft.NET.Sdk' specified could not be found.  E:\Code\MyModule1\MyModule1\_build\_build.csproj
StackTrace:
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.FromProjectRootElement(ProjectRootElement rootElement, ProjectOptions options)
   at Nuke.Common.ProjectModel.ProjectModelTasks.ParseProject(String projectFile, String configuration, String targetFramework)
   at Nuke.Common.Execution.Telemetry.CheckAwareness()
GitHubActions (Build) configuration files have changed.
GitHubActions (Release) configuration files have changed.
GitHubActions (PR_Validation) configuration files have changed.
Press any key to continue...
and then debugging stops at

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=_build
  StackTrace:
   at Build.<get_Restore>b__44_2(DotNetRestoreSettings s) in E:\Code\MyModule1\MyModule1\_build\Build.cs:line 148

**Comment by valadas** [comment]
This one looks to me like a permissions issue, also note that the path should ideally be in a DNN DesktopModules folder, it's not an absolute requirement to package the module but if you run the deploy task, it's what is expected.

To keep things clean, I will close this issue as the original bug report is resolved, if you still experience this problem with Visual Studio running as an administrator, please open a new issue and I'll try to help on that one.
